### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StevenSong** [laddng/LaundryView#2]
Hey I'm trying to make an app similar to this and was wondering how you figured out the api for laundryview? I can't find any documentation on it anywhere..

**Comment by dl-eric** [comment]
I'm looking for the same thing. How did you get the API Key?

**Comment by StevenSong** [comment]
So an API key is specific for a school but it allows you to access the rooms from any school. I ended up just using the API key from OP's app and just input the room ID's for my own school. Not very dynamic since you need to know the room ID's before hand and can't get a list of room's for your school (getting the list of rooms IS specific to the API key) but it works. The project I ended up making is available from my profile, its titled LaundryCheck, if you want to take a look.

**Comment by dl-eric** [comment]
Same, used OP's key too (yikes).

Nice app by the way!

**Comment by umbreon222** [comment]
Hello, I'll comment this for future reference to save the time of anyone who is still wishing to interact with laundry views terrible API. I was analyzing the requests that laundry view is making now with their new revamped site. It seems that the API they are using has updated quite a bit since this app was made, which is expected. It starts out by making a request to "https://www.laundryview.com/api/c_locations" which returns a JSON array of objects that look like:
```json
{
   "school_desc_key":<SCHOOL_ID_STRING>,
   "school_name":<SCHOOL_NAME_STRING>,
   "online":<NUMBER_OF_ONLINE_ROOMS_INT>,
   "total":<NUMBER_OF_ROOMS_INT>
}
```
Once you pick a school name it then makes a request to "https://www.laundryview.com/api/c_room?loc={SCHOOLDESKKEY}" with the key of a school from the previous request. This returns a JSON object that has a large amount of fields but you are most likely interested in the `room_data` field which contains a list of objects that look like:
```json
{
         "school_name":<SCHOOL_NAME_STRING>,
         "campus_name":<CAMPUS_NAME_STRING>,
         "laundry_room_location":<LAUNDRY_ROOM_ID_STRING>,
         "laundry_room_name":<LAUNDRY_ROOM_NAME_STRING>,
         "online":<NUMBER_OF_ONLINE_MACHINES_INT>,
         "total":<NUMBER_OF_MACHINES_INT>
}
```
Once you pick a room it then makes a final request to 
https://www.laundryview.com/api/currentRoomData?school_desc_key={SCHOOLDESKKEY}&location={LOCATIONID}&userContact={PHONENUMBER} with the key of the school we obtained from the first request and the laundry room ID from the second request. The phone number seems to be an optional parameter but I always provide a [random phone number](https://fakenumber.org/). This request returns a JSON object that has alot of newer fields that pertain to the way they lay the machines out in 3D space on the website but the data you are looking for is located in the `objects` field which is a list of laundry machine objects that look like:
```json
{
    "type":"washFL",
    "appliance_type":"W",
    "model_number":"MVW18W",
    "x":-205.3,
    "y":-280.6,
    "orientation":"SE",
    "appliance_desc_key":"95937",
    "appliance_desc":"08",
    "combo":false,
    "stacked":false,
    "opacity":1,
    "status_toggle":2,
    "average_run_time":60,
    "time_remaining":14,
    "time_left_lite":"14 min remaining",
    "percentage":0.3333333333333333
}
```
Hopefully this helps :).
